version: '3.7'

services:

  calendar-frontend:
    container_name: calendar_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/calendar-frontend'
      - '/calendar-frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true